// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qyon.AdventureWorks.Models;

#nullable disable

namespace Qyon.AdventureWorks.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220103215356_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qyon.AdventureWorks.Models.Competidores", b =>
                {
                    b.Property<int>("Id_Competidores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Competidores");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Competidores"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("Altura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("Peso");

                    b.Property<char>("Sexo")
                        .HasColumnType("character(1)")
                        .HasColumnName("Sexo");

                    b.Property<decimal>("TemperaturaMediaCorpo")
                        .HasColumnType("numeric")
                        .HasColumnName("TemperaturaMediaCorpo");

                    b.HasKey("Id_Competidores");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("Qyon.AdventureWorks.Models.HistoricoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Historico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCorrida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCorrida");

                    b.Property<int>("Id_Competidores")
                        .HasColumnType("integer");

                    b.Property<int>("Id_PistaCorrida")
                        .HasColumnType("integer");

                    b.Property<decimal>("TempoGasto")
                        .HasColumnType("numeric")
                        .HasColumnName("TempoGasto");

                    b.HasKey("Id");

                    b.HasIndex("Id_Competidores");

                    b.HasIndex("Id_PistaCorrida");

                    b.ToTable("HistoricoCorrida");
                });

            modelBuilder.Entity("Qyon.AdventureWorks.Models.PistaCorrida", b =>
                {
                    b.Property<int>("Id_PistaCorrida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_PistaCorrida");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_PistaCorrida"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id_PistaCorrida");

                    b.ToTable("PistaCorrida");
                });

            modelBuilder.Entity("Qyon.AdventureWorks.Models.HistoricoCorrida", b =>
                {
                    b.HasOne("Qyon.AdventureWorks.Models.Competidores", "Competidores")
                        .WithMany()
                        .HasForeignKey("Id_Competidores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qyon.AdventureWorks.Models.PistaCorrida", "PistaCorrida")
                        .WithMany()
                        .HasForeignKey("Id_PistaCorrida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competidores");

                    b.Navigation("PistaCorrida");
                });
#pragma warning restore 612, 618
        }
    }
}
